#%RAML 1.0 DataType 
type: object
properties:
  Reply:
    type: object
    properties:
      GetAvgConsumption:
        type: object
        properties:
          Params:
            type: object
            properties:
              AvgConsumption:
                type: object
                properties:
                  ACCOUNT_NO:
                    type: integer
                    required: false
                  LOCATION_NO:
                    type: integer
                    required: false
                  SERVICE_SEQ:
                    type: integer
                    required: false
                  METER_SEQ:
                    type: integer
                    required: false
                  YEAR:
                    type: integer
                    required: false
                  CALC_TP:
                    type: string
                    required: false
                  AVG_CONS:
                    type: number
                    required: false
                  AVG_PER_DAY:
                    type: number
                    required: false
                  AVG_PERIOD:
                    type: number
                    required: false
                  STATUS:
                    type: string
                    required: false
