#%RAML 1.0 DataType
type: object
# additionalProperties: false
properties:
  Request:
    type: object
    # additionalProperties: false
    properties:
      SetMailingAddress:
        type: object
        # additionalProperties: false
        properties:
          Params:
            type: object
            # additionalProperties: false
            properties:
              PERSON_NO:
              ADDRESS_SEQ:
              ACTIVE_DT:
              INACTIVE_DT:
              ADDRESS_CD:
              BUILDING_NAME:
              HOUSE_NO:
              STREET_PFX_DIR:
              STREET_NM:
              STREET_NM_SFX:
              STREET_SFX_DIR:
              SEC_ADDR_ID:
              SEC_ADDR_RANGE:
              TER_ADDR_ID:
              TER_ADDR_RANGE:
              ADDR_ID_4:
              ADDR_RANGE_4:
              LOCATOR_ID:
              ROUTE_PFX:
              ADDR_ROUTE:
              DELIVERY_INST_TP:
              DELIVERY_INST_NM:
              CITY:
              STATE_CD:
              ZIP_CD:
              PO_BOX_NO:
              COUNTRY_CD:
              IN_CARE_OF:
              ENVELOPE_MEMO:
              SEASON_STR_MTH:
              SEASON_STR_DAY:
              SEASON_END_MTH:
              SEASON_END_DAY:
              ADDRESS_CMTS:
              

              