#%RAML 1.0 DataType 
type: object
properties:
  Reply:
    type: object
    properties:
      GetLocation:
        type: object
        properties:
          Params:
            type: object
            properties:
              LOCATION:
                type: object
                properties:
                  W_SITE_EXTENSION:
                    type: string
                    required: false
                  W_SITE_PHONE:
                    type: string
                    required: false
                  V_SADDRESS:
                    type: string
                    required: false
                  A_GEOLAT:
                    type: number
                    required: false
                  A_GEOLONG:
                    type: number
                    required: false
                  LOCATION_NO:
                    type: integer
                    required: false
                  LOCATION_ID_CUSTOM:
                    type: string
                    required: false
                  LOCATION_CLASS:
                    type: string
                    required: false
                  LOC_CLASS_CHG_DT:
                    type: string
                    required: false
                  FUTURE_LOC_CLASS:
                    type: string
                    required: false
                  LOCATION_STAT:
                    type: string
                    required: false
                  SIC_CD:
                    type: string
                    required: false
                  DISTRICT_CD:
                    type: string
                    required: false
                  NBR_OF_UNITS:
                    type: integer
                    required: false
                  APPRASAL_DISTRICT_NO:
                    type: string
                    required: false
                  BUILDING_NAME:
                    type: string
                    required: false
                  HOUSE_NO:
                    type: integer
                    required: false
                  STREET_PFX_DIR:
                    type: string
                    required: false
                  STREET_NM:
                    type: string
                    required: false
                  STREET_NM_SFX:
                    type: string
                    required: false
                  STREET_SFX_DIR:
                    type: string
                    required: false
                  SEC_ADDR_ID:
                    type: string
                    required: false
                  SEC_ADDR_RANGE:
                    type: string
                    required: false
                  TER_ADDR_ID:
                    type: string
                    required: false
                  TER_ADDR_RANGE:
                    type: string
                    required: false
                  ADDR_ID_4:
                    type: string
                    required: false
                  ADDR_RANGE_4:
                    type: string
                    required: false
                  LOCATOR_ID:
                    type: string
                    required: false
                  CITY:
                    type: string
                    required: false
                  PROVINCE_CD:
                    type: string
                    required: false
                  POSTAL_CODE:
                    type: integer
                    required: false
                  LIS_CD:
                    type: string
                    required: false
                  LIS_NO:
                    type: string
                    required: false
                  LIS_VALIDAT_STAT:
                    type: integer
                    required: false
                  SC_OLD_LOC_CLASS:
                    type: string
                    required: false
                  SC_NEW_LOC_CLASS:
                    type: string
                    required: false
                  SC_CLASS_CHG_DT:
                    type: string
                    required: false
                  SC_CLASS_CHG_FROM:
                    type: string
                    required: false
                  SELECT_CD:
                    type: string
                    required: false
                  GENERIC_1:
                    type: string
                    required: false
                  GENERIC_2:
                    type: integer
                    required: false
                  GENERIC_3:
                    type: string
                    required: false
                  GENERIC_CD_1:
                    type: string
                    required: false
                  GENERIC_CD_2:
                    type: string
                    required: false
                  GENERIC_CD_3:
                    type: string
                    required: false
                  SPECIAL_DIRECTIONS:
                    type: string
                    required: false
                  ASSET_AREA:
                    type: string
                    required: false
                  ASSET_TYPE:
                    type: string
                    required: false
                  ASSET_NO:
                    type: integer
                    required: false
                  WARD_NO:
                    type: string
                    required: false
                  TAX_ROLL_NO:
                    type: string
                    required: false
                  PARCEL_ID:
                    type: string
                    required: false
                  HOUSE_NO_SEQ:
                    type: string
                    required: false
                  INVALID_ADDRESS_YN:
                    type: string
                    required: false
                  SOURCE_CD:
                    type: string
                    required: false
                  SOURCE_ID:
                    type: string
                    required: false
                  LOCATION_CMTS:
                    type: string
                    required: false
                  STATUS:
                    type: integer
                    required: false
          STATUS:
            type: integer
            required: false