#%RAML 1.0 DataType
type: object
# additionalProperties: false
properties:
  Reply:
    type: object
    # additionalProperties: false
    properties:
      SetAccountPhone:
        type: object
        # additionalProperties: false
        properties:
          Params:
            type: object
            # additionalProperties: false
            properties:
              STATUS:
                type: integer
                example: 0
                required: false
              STATUS_DESC:
                type: string
                example: Account Phone Updated!
                required: false
          STATUS:
            type: integer
            example: 0
            required: false
