#%RAML 1.0 DataType 
type: object
# additionalProperties: false
properties:
  Request:
    type: object
    # additionalProperties: false
    properties:
      AddBillableHoldings:
        type: object
        # additionalProperties: false
        properties:
          Params:
            type: object
            # additionalProperties: false
            properties:
              LOCATION_NO:
                type: integer
                required: true
              SERVICE_TP:
                type: string
                maxLength: 5
                required: true
              ASSET_TP:
                type: string
                maxLength: 5
                required: true
              CONFIG_CD:
                type: string
                maxLength: 5
                required: true
              EFFECTIVE_DT:
                type: string
                required: false
              COUNT:
                type: integer
                required: false
              SEQ_NO:
                type: string
                required: false
              END_DT:
                type: string
                required: false
              GENERIC_1:
                type: string
                maxLength: 50
                required: false
              GENERIC_2:
                type: string
                maxLength: 50
                required: false
              GENERIC_3:
                type: string
                maxLength: 50
                required: false
              GENERIC_4:
                type: string
                maxLength: 50
                required: false
              GENERIC_5:
                type: string
                maxLength: 50
                required: false
              GENERIC_6:
                type: string
                maxLength: 50
                required: false
              GENERIC_7:
                type: string
                maxLength: 50
                required: false
              GENERIC_8:
                type: string
                maxLength: 50
                required: false
              GENERIC_9:
                type: string
                maxLength: 50
                required: false
              GENERIC_10:
                type: string
                maxLength: 50
                required: false
              SIC_CD:
                type: string
                maxLength: 10
                required: false
              AREA_SERVED:
                type: string
                maxLength: 10
                required: false
              COMMENTS:
                type: string
                maxLength: 2000
                required: false
              START_BILL_DT:
                type: string
                required: false
              STOP_BILL_DT:
                type: string
                required: false