#%RAML 1.0 DataType 
type: object
properties:
  Reply:
    type: object
    properties:
      GetPerson:
        type: object
        properties:
          Params:
            type: object
            properties:
              PERSON:
                type: object
                properties:
                  V_PARSE_NAME:
                    type: string
                    required: false
                  O_FEN:
                    type: string
                    required: false
                  PIN:
                    type: string
                    required: false
                  I_DRIVERS_LIC_NO:
                    type: string
                    required: false
                  I_SIN:
                    type: string
                    required: false
                  PERSON_NO:
                    type: integer
                    required: false
                  PRIVATE_YN:
                    type: string
                    required: false
                  PERSON_ID_CUSTOM:
                    type: integer
                    required: false
                  PERSON_STAT:
                    type: string
                    required: false
                  TITLE_CD:
                    type: string
                    required: false
                  PERSON_FNM:
                    type: string
                    required: false
                  PERSON_MNM:
                    type: string
                    required: false
                  PERSON_LNM:
                    type: string
                    required: false
                  ADDR_SEQ_DFLT:
                    type: integer
                    required: false
                  PHONE_SEQ_DFLT:
                    type: integer
                    required: false
                  IN_CARE_OF_OVRD:
                    type: string
                    required: false
                  ENVELOPE_MEMO_OVRD:
                    type: string
                    required: false
                  BIRTH_INC_DT:
                    type: string
                    required: false
                  I_DRIVERS_LIC_PROV:
                    type: string
                    required: false
                  I_GENDER:
                    type: string
                    required: false
                  O_BUSINESS_TP:
                    type: string
                    required: false
                  SELECT_CD:
                    type: string
                    required: false
                  BANKRUPT_YN:
                    type: string
                    required: false
                  BANKRUPT_EXPIRY_DT:
                    type: string
                    required: false
                  PENALTY_DEPOSIT_YN:
                    type: string
                    required: false
                  GENERIC_1:
                    type: string
                    required: false
                  GENERIC_2:
                    type: string
                    required: false
                  GENERIC_3:
                    type: string
                    required: false
                  VOTING_DSCT:
                    type: string
                    required: false
                  LOGIN_NM:
                    type: string
                    required: false
                  HASH_NM:
                    type: string
                    required: false
                  PERSON_CMTS:
                    type: string
                    required: false
                  V_NAME:
                    type: string
                    required: false
                  STATUS:
                    type: integer
                    required: false
          STATUS:
            type: integer
            required: false